[View in Colaboratory](https://colab.research.google.com/github/hariharasudan017/Machine_learning_inkers_lab/blob/master/complete_code_of_assignment2b.ipynb)

In [80]:
import numpy as np
from numpy import array,exp,round
import math

def sigmoid(x):
    sigma =1/(1+np.exp(-x))
    return sigma

def deriv_sigmoid(x):
    d=x*(1-x)
    return d

#wh=np.array([[0.42,0.88,0.55],[0.10,0.73,0.68],[0.60,0.18,0.47],[0.92,0.11,0.52]])
#bh=np.array([0.46,0.72,0.08])
#wout=np.array([[0.30],[0.25],[0.23]])
#bout=np.array([0.69])

wh=np.random.rand(4,3)
bh=np.random.rand(1,3)
wout=np.random.rand(3,1)
bout=np.random.rand(1)
y=np.array([[1],[1],[0]])
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
wh=round(wh, 2)
bh=round(bh, 2)
wout=round(wout, 2)
bout=round(bout, 2)
print(wh)
print(bh)
print(wout)
print(bout)

hidden_layer_input= (X.dot(wh))+bh
print(hidden_layer_input)

hidden_layer_activation=sigmoid(hidden_layer_input)
hidden_layer_activation= round(hidden_layer_activation, 2)
print(hidden_layer_activation)

output_layer_input=(hidden_layer_activation.dot(wout))+bout
output_layer_input=round(output_layer_input, 2)
print(output_layer_input)

output=sigmoid(output_layer_input)
output=round(output, 2)
print(output)

output=np.reshape(output,(3,1))
error=y-output
print(error)

slope_output_layer=deriv_sigmoid(output)
slope_output_layer=round(slope_output_layer, 2)
print(slope_output_layer)

slope_hidden_layer=deriv_sigmoid(hidden_layer_activation)
slope_hidden_layer=round(slope_hidden_layer, 2)
print(slope_hidden_layer)

lr=1
d_output=error*slope_output_layer
d_output=d_output*lr
d_output=round(d_output, 2)
print(d_output)

Error_at_hidden_layer=np.dot(d_output,wout.T)
print(Error_at_hidden_layer)

d_hidden_layer = Error_at_hidden_layer * slope_hidden_layer
d_hidden_layer =round(d_hidden_layer, 3)
print(d_hidden_layer)

lr= 0.1
wout=wout+np.dot(hidden_layer_activation.T,d_output)*lr
wout=round(wout, 2)
print(wout)

wh=wh+(np.dot(X.T,d_hidden_layer)*lr)
wh=round(wh, 2)
print(wh)

bh=bh+np.sum(d_hidden_layer,axis=0)*lr
print(bh)

bout=bout+np.sum(d_output,axis=0)*lr
bout=round(bout, 2)
print(bout)

[[0.71 0.56 0.27]
 [0.73 0.12 0.36]
 [0.59 0.02 0.51]
 [0.3  0.29 0.45]]
[[0.81 0.04 0.29]]
[[0.16]
 [0.23]
 [0.82]]
[0.52]
[[2.11 0.62 1.07]
 [2.41 0.91 1.52]
 [1.84 0.45 1.1 ]]
[[0.89 0.65 0.74]
 [0.92 0.71 0.82]
 [0.86 0.61 0.75]]
[[1.42]
 [1.5 ]
 [1.41]]
[[0.81]
 [0.82]
 [0.8 ]]
[[ 0.19]
 [ 0.18]
 [-0.8 ]]
[[0.15]
 [0.15]
 [0.16]]
[[0.1  0.23 0.19]
 [0.07 0.21 0.15]
 [0.12 0.24 0.19]]
[[ 0.03]
 [ 0.03]
 [-0.13]]
[[ 0.0048  0.0069  0.0246]
 [ 0.0048  0.0069  0.0246]
 [-0.0208 -0.0299 -0.1066]]
[[ 0.     0.002  0.005]
 [ 0.     0.001  0.004]
 [-0.002 -0.007 -0.02 ]]
[[0.15]
 [0.23]
 [0.81]]
[[0.71 0.56 0.27]
 [0.73 0.12 0.36]
 [0.59 0.02 0.51]
 [0.3  0.29 0.45]]
[[0.8098 0.0396 0.2889]]
[0.51]
